### ISSUE TITLE
[BUG] CCExtractor version 16 issue title here

### ISSUE THREAD

**Issue by satyammittal** [satyammittal/library#7]
In raising this issue, I confirm the following (please check boxes, eg [X]):

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn&#39;t already present.
- [X] I have checked that the issue I&#39;m posting isn&#39;t already reported.
- [X] I have checked that the issue I&#39;m porting isn&#39;t already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [X] I have used the latest available version of CCExtractor to verify this issue exists.

My familiarity with the project is as follows (check one, eg [X]):

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [X] I am an active contributor to CCExtractor.

**Necessary information** 
 What platform did you use? windows 
 What where the used arguments? -autoprogram 
**Video links** 
 [Sample Link](ns398219.ip-37-59-37.eu/sample/145) 
 hello,notes here 
**Additional information**
issue content here
